// src/templates/svelteIconTemplate.js
export function createSvelteIconComponent(optimizedSvg, baseClass) {
  return `<script lang="ts">
  // Generated by svg-to-svelte-icons
  import type { SVGAttributes } from 'svelte/elements';
  interface $$Props extends SVGAttributes<SVGSVGElement> {}
  const baseClassName = "${baseClass || ''}";
  $: finalClass = (baseClassName + ' ' + ($$props.class || '')).trim();
</script>
${optimizedSvg.replace(/<svg([^>]*)>/, (match, attributes) => {
    const existingClassMatch = attributes.match(/class="([^"]*)"/);
    const existingClass = existingClassMatch ? existingClassMatch[1] : "";
    const combinedClass = (existingClass + ' ' + '{finalClass}').trim();
    const newAttributes = attributes.replace(/class="([^"]*)"/, '').trim();
    return `<svg ${newAttributes} {...$$props} class="${combinedClass}">`;
  })}
`;
}